# Generated by Django 2.0.4 on 2018-04-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Pesagem')),
                ('peso', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso')),
            ],
            options={
                'verbose_name_plural': 'Pesos',
                'verbose_name': 'Peso',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('apelido', models.CharField(max_length=20, verbose_name='Apelido')),
                ('login', models.CharField(max_length=300, verbose_name='Usuário/e-mail')),
                ('senha', models.CharField(max_length=12, verbose_name='Senha')),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'verbose_name': 'Pessoa',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='peso',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Pessoa', verbose_name='Pessoa'),
        ),
    ]
