# Generated by Django 2.0.4 on 2018-04-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
