# Generated by Django 2.0.4 on 2018-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20180421_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='slug'),
        ),
    ]
